In [1]:
from keras.models import Sequential, Model, Input
from keras.layers import Concatenate, Dense
import numpy as np

/Users/jeremy.zhang/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
/Users/jeremy.zhang/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)


In [17]:
model = Sequential()
model.add(Dense(1, input_shape=(3,)))

In [2]:
x = np.array([1, 2, 3]).reshape(1, 3)
x.shape

(1, 3)

In [18]:
model.predict(x)

array([[2.0137918]], dtype=float32)

#### Concatenate
This is not suited for sequential models, unless the previous layer outputs a list (this is possible but not common).

In [36]:
x

array([[1, 2, 3]])

In [9]:
import keras.backend as K

In [16]:
inp = Input(shape=(3,))
cat = Concatenate(axis=1)([inp, inp])
output = Dense(1)(cat)

model = Model(inputs=[inp], outputs=[output])

In [17]:
model.predict(x)

array([[-3.7107625]], dtype=float32)

In [20]:
cat.shape

TensorShape([Dimension(None), Dimension(6)])