https://keras.io/layers/wrappers/

In [49]:
from keras.models import Sequential
from keras.layers import Dense, TimeDistributed
from keras.layers import LSTM
import numpy as np
import random

#### Basic LSTM Model

In [9]:
m = Sequential()
m.add(LSTM(5, input_shape=(3, 1)))

In [10]:
inp = np.array([[1], [2], [0]]).reshape(1, 3, 1)
pred = m.predict(inp)
pred

array([[-0.06902287,  0.13025649,  0.00734532, -0.15845421,  0.06184174]],
      dtype=float32)

In [6]:
pred.shape

(1, 5)

#### LSTM with returen sequences
Makes prediction for each time stamp

In [14]:
m = Sequential()
m.add(LSTM(5, input_shape=(3, 1), return_sequences=True))

In [15]:
inp = np.array([[1], [2], [0]]).reshape(1, 3, 1)
pred = m.predict(inp)
pred

array([[[ 0.12415466, -0.03527911, -0.03167204,  0.00175173,
          0.1140329 ],
        [ 0.25751117, -0.07527899, -0.06301902,  0.00250919,
          0.34441563],
        [ 0.15621203, -0.07422133, -0.07741755, -0.00914326,
          0.20227769]]], dtype=float32)

In [16]:
pred.shape

(1, 3, 5)

#### Add TimeDistributed Layer
Dense layer applied on each time stamp

In [48]:
seed(1)
m = Sequential()
m.add(LSTM(5, input_shape=(3, 1), return_sequences=True))
m.add(Dense(1))

inp = np.array([[1], [2], [0]]).reshape(1, 3, 1)
pred = m.predict(inp)
pred

array([[[0.16985919],
        [0.39878365],
        [0.3418519 ]]], dtype=float32)

In [23]:
pred.shape

(1, 3, 1)

In [39]:
seed(1)
m = Sequential()
m.add(LSTM(5, input_shape=(3, 1), return_sequences=True))
m.add(TimeDistributed(Dense(1)))

inp = np.array([[1], [2], [0]]).reshape(1, 3, 1)
pred = m.predict(inp)
pred

array([[[0.09979038],
        [0.2478514 ],
        [0.08143747]]], dtype=float32)

In [31]:
pred.shape

(1, 3, 1)